version: "2"

services:
  server:
    build: app/
    command: python3.9 ./app.py
  restarter:
    image: docker
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command: [ "/bin/sh", "-c", "while true; do sleep 43200; docker restart pyrogramtaskmanager_server_1; done" ]
    restart: unless-stopped
